# Generated by Django 4.1.6 on 2024-03-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_sitebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='tab_logo',
            field=models.ImageField(default='', upload_to='images/site_setting', verbose_name='لوگو تب'),
        ),
    ]
