# Generated by Django 4.1.6 on 2024-03-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_sitesetting_tab_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='tab_logo',
        ),
    ]
